#/***************************************************************************
#*                      ZBOSS ZigBee Pro 2007 stack                         *
#*                                                                          *
#*          Copyright (c) 2012 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*          Copyright (c) 2011 ClarIDy Solutions, Inc., Taipei, Taiwan.     *
#*                       http://www.claridy.com/                            *
#*                                                                          *
#*          Copyright (c) 2011 Uniband Electronic Corporation (UBEC),       *
#*                             Hsinchu, Taiwan.                             *
#*                       http://www.ubec.com.tw/                            *
#*                                                                          *
#*          Copyright (c) 2011 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*                                                                          *
#*                                                                          *
#* ZigBee Pro 2007 stack, also known as ZBOSS (R) ZB stack is available     *
#* under either the terms of the Commercial License or the GNU General      *
#* Public License version 2.0.  As a recipient of ZigBee Pro 2007 stack, you*
#* may choose which license to receive this code under (except as noted in  *
#* per-module LICENSE files).                                               *
#*                                                                          *
#* ZBOSS is a registered trademark of DSR Corporation AKA Data Storage      *
#* Research LLC.                                                            *
#*                                                                          *
#* GNU General Public License Usage                                         *
#* This file may be used under the terms of the GNU General Public License  *
#* version 2.0 as published by the Free Software Foundation and appearing   *
#* in the file LICENSE.GPL included in the packaging of this file.  Please  *
#* review the following information to ensure the GNU General Public        *
#* License version 2.0 requirements will be met:                            *
#* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html.                   *
#*                                                                          *
#* Commercial Usage                                                         *
#* Licensees holding valid ClarIDy/UBEC/DSR Commercial licenses may use     *
#* this file in accordance with the ClarIDy/UBEC/DSR Commercial License     *
#* Agreement provided with the Software or, alternatively, in accordance    *
#* with the terms contained in a written agreement between you and          *
#* ClarIDy/UBEC/DSR.                                                        *
#*                                                                          *
#****************************************************************************
# PURPOSE: NWK passive ack test.
#*/

nwk_passive_ack_SRCS1 := tests/nwk_passive_ack/nwk_passive_ack_zc.c
nwk_passive_ack_OBJS1 := $(call objs4srcs,$(nwk_passive_ack_SRCS1),zc)
test_zc_OBJS += $(nwk_passive_ack_OBJS1)

nwk_passive_ack_SRCS2 := tests/nwk_passive_ack/nwk_passive_ack_zed2.c
nwk_passive_ack_OBJS2 := $(call objs4srcs,$(nwk_passive_ack_SRCS2),ze)
test_ze_OBJS += $(nwk_passive_ack_OBJS2)

nwk_passive_ack_SRCS3 := tests/nwk_passive_ack/nwk_passive_ack_zr1.c
nwk_passive_ack_OBJS3 := $(call objs4srcs,$(nwk_passive_ack_SRCS3),zc)
test_zc_OBJS += $(nwk_passive_ack_OBJS3)

nwk_passive_ack_SRCS4 := tests/nwk_passive_ack/nwk_passive_ack_zr3.c
nwk_passive_ack_OBJS4 := $(call objs4srcs,$(nwk_passive_ack_SRCS4),zc)
test_zc_OBJS += $(nwk_passive_ack_OBJS4)

nwk_passive_ack_BIN1 := tests/nwk_passive_ack/nwk_passive_ack_zc$(EXE)
nwk_passive_ack_BIN2 := tests/nwk_passive_ack/nwk_passive_ack_zed2$(EXE)
nwk_passive_ack_BIN3 := tests/nwk_passive_ack/nwk_passive_ack_zr1$(EXE)
nwk_passive_ack_BIN4 := tests/nwk_passive_ack/nwk_passive_ack_zr3$(EXE)

$(nwk_passive_ack_BIN1) : $(nwk_passive_ack_OBJS1)  $(call libzboss_name,zc)
	$(call link_binary)

$(nwk_passive_ack_BIN2) : $(nwk_passive_ack_OBJS2)  $(call libzboss_name,ze)
	$(call link_binary)

$(nwk_passive_ack_BIN3) : $(nwk_passive_ack_OBJS3)  $(call libzboss_name,zc)
	$(call link_binary)

$(nwk_passive_ack_BIN4) : $(nwk_passive_ack_OBJS4)  $(call libzboss_name,zc)
	$(call link_binary)

zboss_TESTS += $(nwk_passive_ack_BIN1) $(nwk_passive_ack_BIN2) \
							 $(nwk_passive_ack_BIN3) $(nwk_passive_ack_BIN4)
