#/***************************************************************************
#*                      ZBOSS ZigBee Pro 2007 stack                         *
#*                                                                          *
#*          Copyright (c) 2012 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*          Copyright (c) 2011 ClarIDy Solutions, Inc., Taipei, Taiwan.     *
#*                       http://www.claridy.com/                            *
#*                                                                          *
#*          Copyright (c) 2011 Uniband Electronic Corporation (UBEC),       *
#*                             Hsinchu, Taiwan.                             *
#*                       http://www.ubec.com.tw/                            *
#*                                                                          *
#*          Copyright (c) 2011 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*                                                                          *
#*                                                                          *
#* ZigBee Pro 2007 stack, also known as ZBOSS (R) ZB stack is available     *
#* under either the terms of the Commercial License or the GNU General      *
#* Public License version 2.0.  As a recipient of ZigBee Pro 2007 stack, you*
#* may choose which license to receive this code under (except as noted in  *
#* per-module LICENSE files).                                               *
#*                                                                          *
#* ZBOSS is a registered trademark of DSR Corporation AKA Data Storage      *
#* Research LLC.                                                            *
#*                                                                          *
#* GNU General Public License Usage                                         *
#* This file may be used under the terms of the GNU General Public License  *
#* version 2.0 as published by the Free Software Foundation and appearing   *
#* in the file LICENSE.GPL included in the packaging of this file.  Please  *
#* review the following information to ensure the GNU General Public        *
#* License version 2.0 requirements will be met:                            *
#* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html.                   *
#*                                                                          *
#* Commercial Usage                                                         *
#* Licensees holding valid ClarIDy/UBEC/DSR Commercial licenses may use     *
#* this file in accordance with the ClarIDy/UBEC/DSR Commercial License     *
#* Agreement provided with the Software or, alternatively, in accordance    *
#* with the terms contained in a written agreement between you and          *
#* ClarIDy/UBEC/DSR.                                                        *
#*                                                                          *
#****************************************************************************
# PURPOSE: ZDO join duration test.
#*/

zdo_join_duration_SRCS1 := tests/zdo_join_duration/zdo_join_duration_zc.c
zdo_join_duration_OBJS1 := $(call objs4srcs,$(zdo_join_duration_SRCS1),zc)
test_zc_OBJS += $(zdo_join_duration_OBJS1)

zdo_join_duration_SRCS2 := tests/zdo_join_duration/zdo_join_duration_zed1.c
zdo_join_duration_OBJS2 := $(call objs4srcs,$(zdo_join_duration_SRCS2),ze)
test_ze_OBJS += $(zdo_join_duration_OBJS2)

zdo_join_duration_SRCS3 := tests/zdo_join_duration/zdo_join_duration_zed2.c
zdo_join_duration_OBJS3 := $(call objs4srcs,$(zdo_join_duration_SRCS3),ze)
test_ze_OBJS += $(zdo_join_duration_OBJS3)

zdo_join_duration_BIN1 := tests/zdo_join_duration/zdo_join_duration_zc$(EXE)
zdo_join_duration_BIN2 := tests/zdo_join_duration/zdo_join_duration_zed1$(EXE)
zdo_join_duration_BIN3 := tests/zdo_join_duration/zdo_join_duration_zed2$(EXE)

$(zdo_join_duration_BIN1) : $(zdo_join_duration_OBJS1)  $(call libzboss_name,zc)
	$(LINK_BINARY)

$(zdo_join_duration_BIN2) : $(zdo_join_duration_OBJS2)  $(call libzboss_name,ze)
	$(LINK_BINARY)

$(zdo_join_duration_BIN3) : $(zdo_join_duration_OBJS3)  $(call libzboss_name,ze)
	$(LINK_BINARY)

zboss_TESTS += $(zdo_join_duration_BIN1) $(zdo_join_duration_BIN2) $(zdo_join_duration_BIN3)
